FROM oraclelinux:9

ARG playbook=dpdk_devel
ENV LANG en_US.UTF-8

WORKDIR /work
CMD ["/bin/bash"]

COPY ansible /ansible

RUN dnf update -y \
	&& dnf install -y python3 ansible-core
RUN ANSIBLE_LOCALHOST_WARNING=False \
	ansible-playbook -b /ansible/${playbook}.yml -i /dev/null
