---
- name: dpdk
  include_tasks: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_version}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"
    - "default.yml"
