---
- name: install
  apt:
    name: dpdk
    state: present

- name: install tools
  apt:
    name: dpdk-dev
    state: present
  when: dpdk_install_tools

- name: install dev
  apt:
    name: libdpdk-dev
    state: present
  when: dpdk_install_dev
